language: julia
sudo: required
dist: trusty
julia:
  - 1.5
notifications:
  email: false
before_install:
  - sudo apt-get -qq update
script:
  - julia install.jl
  - julia -e 'using Pkg; Pkg.build(); Pkg.test(coverage=true)'
after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
