language: julia
sudo: required
dist: trusty
julia:
  - 1.0
notifications:
  email: false
before_install:
  - sudo apt-get -qq update
script: # use the default script section which is equivalent to the following
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --check-bounds=yes -e 'using Pkg; Pkg.add("Statistics"); Pkg.add("Printf"); Pkg.clone(pwd()); Pkg.build("AA120Q"); Pkg.test("AA120Q"; coverage=true)'
after_success:
  - julia -e 'cd(@__DIR__); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
